name: my_ledger
description: "A complete offline budgeting app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dots_indicator: ^4.0.1
  
  # State Management
  flutter_riverpod: ^3.2.0
  
  # Database & Storage
  sqflite: ^2.3.2
  path: ^1.9.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  
  # UI & Charts
  fl_chart: ^1.1.1
  google_fonts: ^8.0.0
  font_awesome_flutter: ^10.7.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.3.3
  collection: ^1.18.0
  math_expressions: ^3.1.0
  
  # Features
  local_auth: ^3.0.0
  image_picker: ^1.0.7
  file_picker: ^10.3.8
  share_plus: ^12.0.1
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/